name: Lint Commit Messages
permissions:
  contents: read

on:
    branches:
      - main
      - master
      - develop

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: '.commitlintrc.yml'
